{"uuid": "dd1cbade-54c7-43f7-97e1-4fae01de6565", "children": ["51fd4e3e-b38f-4afd-8c77-d8ed91f7f012"], "befores": [{"name": "function_fixture2", "status": "passed", "start": 1705487003072, "stop": 1705487003072}], "afters": [{"name": "function_fixture2::driver_teardown", "status": "broken", "statusDetails": {"message": "AttributeError: 'NoneType' object has no attribute 'close_app'\n", "trace": "  File \"/Users/hpc/pytest/venv/lib/python3.10/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Users/hpc/pytest/conftest.py\", line 25, in driver_teardown\n    request.instance.driver.close_app()\n"}, "start": 1705487003092, "stop": 1705487003093}], "start": 1705487003072, "stop": 1705487003093}