{"uuid": "9dbc4f4a-1e92-48f1-99d2-86efd1940587", "children": ["6487946a-126a-41b7-a1fb-de54f1af1df0"], "befores": [{"name": "function_fixture2", "status": "passed", "start": 1705657969999, "stop": 1705657973753}], "afters": [{"name": "function_fixture2::driver_teardown", "status": "broken", "statusDetails": {"message": "AttributeError: 'WebDriver' object has no attribute 'close_app'\n", "trace": "  File \"/Users/hpc/pytest/venv/lib/python3.10/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Users/hpc/pytest/conftest.py\", line 25, in driver_teardown\n    request.instance.driver.close_app()\n"}, "start": 1705657989119, "stop": 1705657989119}], "start": 1705657969999, "stop": 1705657989119}