{"uuid": "ac1d88d9-c41d-4fbf-8cbc-d5be3aa74c5b", "children": ["d5a497f8-6cae-4420-a298-4f8cffc6268d"], "befores": [{"name": "function_fixture2", "status": "passed", "start": 1705649934699, "stop": 1705649934699}], "afters": [{"name": "function_fixture2::driver_teardown", "status": "broken", "statusDetails": {"message": "AttributeError: 'NoneType' object has no attribute 'close_app'\n", "trace": "  File \"/Users/hpc/pytest/venv/lib/python3.10/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Users/hpc/pytest/conftest.py\", line 25, in driver_teardown\n    request.instance.driver.close_app()\n"}, "start": 1705649934719, "stop": 1705649934719}], "start": 1705649934699, "stop": 1705649934719}