{"uuid": "c004bf7f-30bb-4b3b-be19-c0ae1460e950", "children": ["cc4aabae-2baf-4b8d-8c71-d68ad305f033"], "befores": [{"name": "function_fixture2", "status": "passed", "start": 1705657408317, "stop": 1705657416075}], "afters": [{"name": "function_fixture2::driver_teardown", "status": "broken", "statusDetails": {"message": "AttributeError: 'NoneType' object has no attribute 'close_app'\n", "trace": "  File \"/Users/hpc/pytest/venv/lib/python3.10/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Users/hpc/pytest/conftest.py\", line 25, in driver_teardown\n    request.instance.driver.close_app()\n"}, "start": 1705657416119, "stop": 1705657416119}], "start": 1705657408317, "stop": 1705657416119}