{"uuid": "8e022395-3de0-4c92-bff1-81be3a4dc165", "children": ["42d706eb-dfc3-42b6-87b2-37d1a4565610"], "befores": [{"name": "function_fixture2", "status": "passed", "start": 1705653605743, "stop": 1705653605745}], "afters": [{"name": "function_fixture2::driver_teardown", "status": "broken", "statusDetails": {"message": "AttributeError: 'NoneType' object has no attribute 'close_app'\n", "trace": "  File \"/Users/hpc/pytest/venv/lib/python3.10/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Users/hpc/pytest/conftest.py\", line 25, in driver_teardown\n    request.instance.driver.close_app()\n"}, "start": 1705653605765, "stop": 1705653605765}], "start": 1705653605743, "stop": 1705653605765}