{"uuid": "cca599fb-6095-4398-911d-50c648fe07e3", "children": ["16b3c820-44f6-493d-a5f5-73f5c829fe40"], "befores": [{"name": "function_fixture2", "status": "passed", "start": 1705658198342, "stop": 1705658202172}], "afters": [{"name": "function_fixture2::driver_teardown", "status": "broken", "statusDetails": {"message": "AttributeError: 'WebDriver' object has no attribute 'close_app'\n", "trace": "  File \"/Users/hpc/pytest/venv/lib/python3.10/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Users/hpc/pytest/conftest.py\", line 25, in driver_teardown\n    request.instance.driver.close_app()\n"}, "start": 1705658261309, "stop": 1705658261309}], "start": 1705658198342, "stop": 1705658261309}